IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'AOTBEDDING\KVadlamudi')
CREATE LOGIN [AOTBEDDING\KVadlamudi] FROM WINDOWS
GO
CREATE USER [AOTBEDDING\KVadlamudi] FOR LOGIN [AOTBEDDING\KVadlamudi]
GO
